// src/lib/countryUtils.ts

// THIS IS THE FIX: We are now using image URLs instead of emoji characters.
const countryMap: Record<string, { name: string; flag: string }> = {
    AE: { name: 'United Arab Emirates', flag: 'https://flagcdn.com/w40/ae.png' },
    AL: { name: 'Albania', flag: 'https://flagcdn.com/w40/al.png' },
    AR: { name: 'Argentina', flag: 'https://flagcdn.com/w40/ar.png' },
    AT: { name: 'Austria', flag: 'https://flagcdn.com/w40/at.png' },
    AU: { name: 'Australia', flag: 'https://flagcdn.com/w40/au.png' },
    AW: { name: 'Aruba', flag: 'https://flagcdn.com/w40/aw.png' },
    AZ: { name: 'Azerbaijan', flag: 'https://flagcdn.com/w40/az.png' },
    BA: { name: 'Bosnia and Herzegovina', flag: 'https://flagcdn.com/w40/ba.png' },
    BD: { name: 'Bangladesh', flag: 'https://flagcdn.com/w40/bd.png' },
    BE: { name: 'Belgium', flag: 'https://flagcdn.com/w40/be.png' },
    BG: { name: 'Bulgaria', flag: 'https://flagcdn.com/w40/bg.png' },
    BH: { name: 'Bahrain', flag: 'https://flagcdn.com/w40/bh.png' },
    BJ: { name: 'Benin', flag: 'https://flagcdn.com/w40/bj.png' },
    BN: { name: 'Brunei Darussalam', flag: 'https://flagcdn.com/w40/bn.png' },
    BO: { name: 'Bolivia', flag: 'https://flagcdn.com/w40/bo.png' },
    BQ: { name: 'Bonaire, Sint Eustatius and Saba', flag: 'https://flagcdn.com/w40/bq.png' },
    BR: { name: 'Brazil', flag: 'https://flagcdn.com/w40/br.png' },
    BS: { name: 'Bahamas', flag: 'https://flagcdn.com/w40/bs.png' },
    BY: { name: 'Belarus', flag: 'https://flagcdn.com/w40/by.png' },
    BZ: { name: 'Belize', flag: 'https://flagcdn.com/w40/bz.png' },
    CA: { name: 'Canada', flag: 'https://flagcdn.com/w40/ca.png' },
    CF: { name: 'Central African Republic', flag: 'https://flagcdn.com/w40/cf.png' },
    CH: { name: 'Switzerland', flag: 'https://flagcdn.com/w40/ch.png' },
    CL: { name: 'Chile', flag: 'https://flagcdn.com/w40/cl.png' },
    CN: { name: 'China', flag: 'https://flagcdn.com/w40/cn.png' },
    CR: { name: 'Costa Rica', flag: 'https://flagcdn.com/w40/cr.png' },
    CV: { name: 'Cabo Verde', flag: 'https://flagcdn.com/w40/cv.png' },
    CY: { name: 'Cyprus', flag: 'https://flagcdn.com/w40/cy.png' },
    DE: { name: 'Germany', flag: 'https://flagcdn.com/w40/de.png' },
    DO: { name: 'Dominican Republic', flag: 'https://flagcdn.com/w40/do.png' },
    EE: { name: 'Estonia', flag: 'https://flagcdn.com/w40/ee.png' },
    EG: { name: 'Egypt', flag: 'https://flagcdn.com/w40/eg.png' },
    ES: { name: 'Spain', flag: 'https://flagcdn.com/w40/es.png' },
    ET: { name: 'Ethiopia', flag: 'https://flagcdn.com/w40/et.png' },
    GB: { name: 'United Kingdom', flag: 'https://flagcdn.com/w40/gb.png' },
    GD: { name: 'Grenada', flag: 'https://flagcdn.com/w40/gd.png' },
    GE: { name: 'Georgia', flag: 'https://flagcdn.com/w40/ge.png' },
    GR: { name: 'Greece', flag: 'https://flagcdn.com/w40/gr.png' },
    GT: { name: 'Guatemala', flag: 'https://flagcdn.com/w40/gt.png' },
    GW: { name: 'Guinea-Bissau', flag: 'https://flagcdn.com/w40/gw.png' },
    GY: { name: 'Guyana', flag: 'https://flagcdn.com/w40/gy.png' },
    HK: { name: 'Hong Kong', flag: 'https://flagcdn.com/w40/hk.png' },
    HR: { name: 'Croatia', flag: 'https://flagcdn.com/w40/hr.png' },
    HU: { name: 'Hungary', flag: 'https://flagcdn.com/w40/hu.png' },
    ID: { name: 'Indonesia', flag: 'https://flagcdn.com/w40/id.png' },
    IE: { name: 'Ireland', flag: 'https://flagcdn.com/w40/ie.png' },
    IN: { name: 'India', flag: 'https://flagcdn.com/w40/in.png' },
    IS: { name: 'Iceland', flag: 'https://flagcdn.com/w40/is.png' },
    IT: { name: 'Italy', flag: 'https://flagcdn.com/w40/it.png' },
    JM: { name: 'Jamaica', flag: 'https://flagcdn.com/w40/jm.png' },
    JP: { name: 'Japan', flag: 'https://flagcdn.com/w40/jp.png' },
    KE: { name: 'Kenya', flag: 'https://flagcdn.com/w40/ke.png' },
    KH: { name: 'Cambodia', flag: 'https://flagcdn.com/w40/kh.png' },
    KR: { name: 'South Korea', flag: 'https://flagcdn.com/w40/kr.png' },
    KW: { name: 'Kuwait', flag: 'https://flagcdn.com/w40/kw.png' },
    KY: { name: 'Cayman Islands', flag: 'https://flagcdn.com/w40/ky.png' },
    KZ: { name: 'Kazakhstan', flag: 'https://flagcdn.com/w40/kz.png' },
    LA: { name: 'Laos', flag: 'https://flagcdn.com/w40/la.png' },
    LB: { name: 'Lebanon', flag: 'https://flagcdn.com/w40/lb.png' },
    LI: { name: 'Liechtenstein', flag: 'https://flagcdn.com/w40/li.png' },
    LT: { name: 'Lithuania', flag: 'https://flagcdn.com/w40/lt.png' },
    LU: { name: 'Luxembourg', flag: 'https://flagcdn.com/w40/lu.png' },
    LV: { name: 'Latvia', flag: 'https://flagcdn.com/w40/lv.png' },
    MA: { name: 'Morocco', flag: 'https://flagcdn.com/w40/ma.png' },
    MD: { name: 'Moldova', flag: 'https://flagcdn.com/w40/md.png' },
    ME: { name: 'Montenegro', flag: 'https://flagcdn.com/w40/me.png' },
    MG: { name: 'Madagascar', flag: 'https://flagcdn.com/w40/mg.png' },
    MK: { name: 'North Macedonia', flag: 'https://flagcdn.com/w40/mk.png' },
    MM: { name: 'Myanmar', flag: 'https://flagcdn.com/w40/mm.png' },
    MO: { name: 'Macao', flag: 'https://flagcdn.com/w40/mo.png' },
    MQ: { name: 'Martinique', flag: 'https://flagcdn.com/w40/mq.png' },
    MT: { name: 'Malta', flag: 'https://flagcdn.com/w40/mt.png' },
    MX: { name: 'Mexico', flag: 'https://flagcdn.com/w40/mx.png' },
    MY: { name: 'Malaysia', flag: 'https://flagcdn.com/w40/my.png' },
    NG: { name: 'Nigeria', flag: 'https://flagcdn.com/w40/ng.png' },
    NI: { name: 'Nicaragua', flag: 'https://flagcdn.com/w40/ni.png' },
    NL: { name: 'Netherlands', flag: 'https://flagcdn.com/w40/nl.png' },
    NO: { name: 'Norway', flag: 'https://flagcdn.com/w40/no.png' },
    NP: { name: 'Nepal', flag: 'https://flagcdn.com/w40/np.png' },
    NZ: { name: 'New Zealand', flag: 'https://flagcdn.com/w40/nz.png' },
    PE: { name: 'Peru', flag: 'https://flagcdn.com/w40/pe.png' },
    PH: { name: 'Philippines', flag: 'https://flagcdn.com/w40/ph.png' },
    PL: { name: 'Poland', flag: 'https://flagcdn.com/w40/pl.png' },
    PR: { name: 'Puerto Rico', flag: 'https://flagcdn.com/w40/pr.png' },
    PS: { name: 'Palestine', flag: 'https://flagcdn.com/w40/ps.png' },
    PT: { name: 'Portugal', flag: 'https://flagcdn.com/w40/pt.png' },
    PY: { name: 'Paraguay', flag: 'https://flagcdn.com/w40/py.png' },
    RO: { name: 'Romania', flag: 'https://flagcdn.com/w40/ro.png' },
    RS: { name: 'Serbia', flag: 'https://flagcdn.com/w40/rs.png' },
    RU: { name: 'Russia', flag: 'https://flagcdn.com/w40/ru.png' },
    SA: { name: 'Saudi Arabia', flag: 'https://flagcdn.com/w40/sa.png' },
    SE: { name: 'Sweden', flag: 'https://flagcdn.com/w40/se.png' },
    SG: { name: 'Singapore', flag: 'https://flagcdn.com/w40/sg.png' },
    SI: { name: 'Slovenia', flag: 'https://flagcdn.com/w40/si.png' },
    SK: { name: 'Slovakia', flag: 'https://flagcdn.com/w40/sk.png' },
    SL: { name: 'Sierra Leone', flag: 'https://flagcdn.com/w40/sl.png' },
    SS: { name: 'South Sudan', flag: 'https://flagcdn.com/w40/ss.png' },
    TG: { name: 'Togo', flag: 'https://flagcdn.com/w40/tg.png' },
    TH: { name: 'Thailand', flag: 'https://flagcdn.com/w40/th.png' },
    TJ: { name: 'Tajikistan', flag: 'https://flagcdn.com/w40/tj.png' },
    TL: { name: 'Timor-Leste', flag: 'https://flagcdn.com/w40/tl.png' },
    TN: { name: 'Tunisia', flag: 'https://flagcdn.com/w40/tn.png' },
    TR: { name: 'Turkey', flag: 'https://flagcdn.com/w40/tr.png' },
    TT: { name: 'Trinidad and Tobago', flag: 'https://flagcdn.com/w40/tt.png' },
    TW: { name: 'Taiwan', flag: 'https://flagcdn.com/w40/tw.png' },
    UA: { name: 'Ukraine', flag: 'https://flagcdn.com/w40/ua.png' },
    US: { name: 'United States', flag: 'https://flagcdn.com/w40/us.png' },
    UY: { name: 'Uruguay', flag: 'https://flagcdn.com/w40/uy.png' },
    VE: { name: 'Venezuela', flag: 'https://flagcdn.com/w40/ve.png' },
    VG: { name: 'British Virgin Islands', flag: 'https://flagcdn.com/w40/vg.png' },
    VN: { name: 'Vietnam', flag: 'https://flagcdn.com/w40/vn.png' },
    VU: { name: 'Vanuatu', flag: 'https://flagcdn.com/w40/vu.png' },
    XK: { name: 'Kosovo', flag: 'https://flagcdn.com/w40/xk.png' },
    ZA: { name: 'South Africa', flag: 'https://flagcdn.com/w40/za.png' },
    ZW: { name: 'Zimbabwe', flag: 'https://flagcdn.com/w40/zw.png' },
    world: { name: 'Worldwide', flag: '🌍' }, // The globe emoji is fine
};

export const getCountryInfo = (code: string) => {
    return countryMap[code.toUpperCase()] || null;
};